import "dotenv/config";
import assert from "node:assert/strict";
import { spawn, spawnSync, type ChildProcess } from "node:child_process";
import { randomUUID } from "node:crypto";
import test from "node:test";
import pg from "pg";
import { hashPassword } from "@/server/password";

const port = 3202; const baseUrl = `http://localhost:${port}`;
const dbUrlFor = (source: string, name: string) => { const url = new URL(source); url.pathname = `/${name}`; return url.toString(); };
const quote = (value: string) => { if (!/^[A-Za-z0-9_]+$/.test(value)) throw new Error("Unsafe identifier"); return `"${value}"`; };
async function wait(server: ChildProcess) { const deadline = Date.now() + 30000; while (Date.now() < deadline) { if (server.exitCode !== null) throw new Error(`server exited ${server.exitCode}`); try { await fetch(`${baseUrl}/api/auth/session`); return; } catch { await new Promise((resolve) => setTimeout(resolve, 250)); } } throw new Error("server timeout"); }
function cookies(response: Response) { return response.headers.getSetCookie().map((value) => value.split(";", 1)[0]).join("; "); }
async function login(username: string, password: string) { const response = await fetch(`${baseUrl}/api/auth/login`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ username, password }) }); assert.equal(response.status, 200); const cookie = cookies(response); const session = await fetch(`${baseUrl}/api/auth/session`, { headers: { cookie } }); const body = await session.json() as { csrfToken: string }; return { cookie, csrf: body.csrfToken }; }

test("S4.1 HTTP enforces USER recheck/Admin finalize and CSRF", async (t) => {
  const source = process.env.DATABASE_URL; const adminUrl = process.env.DATABASE_RESTORE_ADMIN_URL;
  if (!source || !adminUrl) { t.skip("DATABASE_URL and DATABASE_RESTORE_ADMIN_URL are required"); return; }
  const suffix = randomUUID().replaceAll("-", "").slice(0, 12); const database = `pbs41${suffix}`; const url = dbUrlFor(source, database); const password = `S41-${suffix}-Password!`; const admin = new pg.Client({ connectionString: adminUrl }); admin.on("error", () => undefined); let server: ChildProcess | undefined;
  try { await admin.connect(); await admin.query(`CREATE DATABASE ${quote(database)} TEMPLATE ${quote(new URL(source).pathname.slice(1))}`); const fixture = new pg.Client({ connectionString: url }); fixture.on("error", () => undefined); await fixture.connect(); const passwordHash = await hashPassword(password); await fixture.query("INSERT INTO users(username, password_hash, role, updated_at) VALUES ($1, $2, 'ADMIN', CURRENT_TIMESTAMP), ($3, $2, 'USER', CURRENT_TIMESTAMP)", [`it_s41_http_admin_${suffix}`, passwordHash, `it_s41_http_user_${suffix}`]); await fixture.end(); server = spawn(process.execPath, ["node_modules/next/dist/bin/next", "dev", "--hostname", "127.0.0.1", "--port", String(port)], { env: { ...process.env, NODE_ENV: "test", DATABASE_URL: url }, stdio: "ignore", windowsHide: true }); await wait(server);
    const user = await login(`it_s41_http_user_${suffix}`, password); const adminSession = await login(`it_s41_http_admin_${suffix}`, password); const createBody = { transactionAt: "2026-10-01T10:00" };
    const noCsrf = await fetch(`${baseUrl}/api/stock-opnames`, { method: "POST", headers: { "content-type": "application/json", cookie: user.cookie, "idempotency-key": `create-no-csrf-${suffix}` }, body: JSON.stringify(createBody) }); assert.equal(noCsrf.status, 403);
    const createdResponse = await fetch(`${baseUrl}/api/stock-opnames`, { method: "POST", headers: { "content-type": "application/json", cookie: user.cookie, origin: baseUrl, "x-csrf-token": user.csrf, "idempotency-key": `create-${suffix}` }, body: JSON.stringify(createBody) }); assert.equal(createdResponse.status, 201); const created = (await createdResponse.json()).stockOpname as { id: string; items: Array<{ sparePartId: string }> }; assert.ok(created.items.length >= 0);
    const recheck = await fetch(`${baseUrl}/api/stock-opnames/${created.id}/recheck`, { method: "POST", headers: { "content-type": "application/json", cookie: user.cookie, origin: baseUrl, "x-csrf-token": user.csrf, "idempotency-key": `recheck-${suffix}` }, body: JSON.stringify({ ...createBody, items: [] }) }); assert.equal(recheck.status, 200);
    const userFinalize = await fetch(`${baseUrl}/api/admin/stock-opnames/${created.id}/finalize`, { method: "POST", headers: { cookie: user.cookie, origin: baseUrl, "x-csrf-token": user.csrf, "idempotency-key": `finalize-user-${suffix}` } }); assert.equal(userFinalize.status, 403);
    const completeRecheck = await fetch(`${baseUrl}/api/stock-opnames/${created.id}/recheck`, { method: "POST", headers: { "content-type": "application/json", cookie: user.cookie, origin: baseUrl, "x-csrf-token": user.csrf, "idempotency-key": `recheck-complete-${suffix}` }, body: JSON.stringify({ ...createBody, items: created.items.map((item) => ({ sparePartId: item.sparePartId, physicalStock: "0" })) }) }); assert.equal(completeRecheck.status, 200);
    const adminFinalize = await fetch(`${baseUrl}/api/admin/stock-opnames/${created.id}/finalize`, { method: "POST", headers: { cookie: adminSession.cookie, origin: baseUrl, "x-csrf-token": adminSession.csrf, "idempotency-key": `finalize-admin-${suffix}` } }); assert.equal(adminFinalize.status, 200); assert.equal((await adminFinalize.json()).stockOpname.status, "FINALIZED");
  } finally { if (server && server.exitCode === null) { if (process.platform === "win32" && server.pid) spawnSync("taskkill", ["/PID", String(server.pid), "/T", "/F"], { windowsHide: true, stdio: "ignore" }); else server.kill("SIGTERM"); } await admin.query("SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname = $1 AND pid <> pg_backend_pid()", [database]).catch(() => undefined); await admin.query(`DROP DATABASE IF EXISTS ${quote(database)}`).catch(() => undefined); await admin.end().catch(() => undefined); }
});
