import "dotenv/config";
import assert from "node:assert/strict";
import { spawn, spawnSync, type ChildProcess } from "node:child_process";
import { randomUUID } from "node:crypto";
import test from "node:test";
import pg from "pg";
import { hashPassword } from "@/server/password";

const port = 3212; const baseUrl = `http://localhost:${port}`;
const dbUrlFor = (source: string, name: string) => { const url = new URL(source); url.pathname = `/${name}`; return url.toString(); };
const quote = (value: string) => { if (!/^[A-Za-z0-9_]+$/.test(value)) throw new Error("Unsafe identifier"); return `"${value}"`; };
const cookies = (response: Response) => response.headers.getSetCookie().map((value) => value.split(";", 1)[0]).join("; ");
async function wait(server: ChildProcess) { const deadline = Date.now() + 30_000; while (Date.now() < deadline) { if (server.exitCode !== null) throw new Error(`User server exited with ${server.exitCode}`); try { await fetch(`${baseUrl}/api/auth/session`); return; } catch { await new Promise((resolve) => setTimeout(resolve, 250)); } } throw new Error("User server timeout"); }
async function login(username: string, password: string) { const response = await fetch(`${baseUrl}/api/auth/login`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ username, password }) }); assert.equal(response.status, 200); const cookie = cookies(response); const session = await fetch(`${baseUrl}/api/auth/session`, { headers: { cookie } }); return { cookie, csrf: (await session.json()).csrfToken as string }; }
function headers(session: { cookie: string; csrf: string }) { return { "content-type": "application/json", cookie: session.cookie, origin: baseUrl, "x-csrf-token": session.csrf }; }

test("User Management HTTP enforces Admin authorization and lifecycle feedback contracts", async (t) => {
  const source = process.env.DATABASE_URL; const adminUrl = process.env.DATABASE_RESTORE_ADMIN_URL;
  if (!source || !adminUrl) { t.skip("DATABASE_URL and DATABASE_RESTORE_ADMIN_URL are required"); return; }
  const suffix = randomUUID().replaceAll("-", "").slice(0, 12); const database = `pbuim${suffix}`; const url = dbUrlFor(source, database); const adminPassword = `Admin-${suffix}-Password!`; const userPassword = `User-${suffix}-Password!`; const resetPassword = `Reset-${suffix}-Password!`; const dbAdmin = new pg.Client({ connectionString: adminUrl }); dbAdmin.on("error", () => undefined); let server: ChildProcess | undefined;
  try {
    await dbAdmin.connect(); await dbAdmin.query(`CREATE DATABASE ${quote(database)} TEMPLATE ${quote(new URL(source).pathname.slice(1))}`); const fixture = new pg.Client({ connectionString: url }); fixture.on("error", () => undefined); await fixture.connect(); const adminHash = await hashPassword(adminPassword); const userHash = await hashPassword(userPassword); await fixture.query("INSERT INTO users(username, password_hash, role, updated_at) VALUES ($1, $2, 'ADMIN', CURRENT_TIMESTAMP), ($3, $4, 'USER', CURRENT_TIMESTAMP), ($5, $2, 'ADMIN', CURRENT_TIMESTAMP)", [`it_uim_admin_${suffix}`, adminHash, `it_uim_user_${suffix}`, userHash, `it_uim_other_admin_${suffix}`]); await fixture.end();
    server = spawn(process.execPath, ["node_modules/next/dist/bin/next", "dev", "--hostname", "127.0.0.1", "--port", String(port)], { env: { ...process.env, NODE_ENV: "test", DATABASE_URL: url }, stdio: "ignore", windowsHide: true }); await wait(server);
    const unauthenticated = await fetch(`${baseUrl}/api/admin/users`); assert.equal(unauthenticated.status, 401);
    const user = await login(`it_uim_user_${suffix}`, userPassword); const denied = await fetch(`${baseUrl}/api/admin/users`, { headers: { cookie: user.cookie } }); assert.equal(denied.status, 403);
    const admin = await login(`it_uim_admin_${suffix}`, adminPassword); const noCsrf = await fetch(`${baseUrl}/api/admin/users`, { method: "POST", headers: { cookie: admin.cookie, "content-type": "application/json" }, body: JSON.stringify({ username: `new_${suffix}`, password: resetPassword, role: "USER" }) }); assert.equal(noCsrf.status, 403);
    const username = `new_${suffix}`; const createdResponse = await fetch(`${baseUrl}/api/admin/users`, { method: "POST", headers: headers(admin), body: JSON.stringify({ username, password: resetPassword, role: "USER" }) }); assert.equal(createdResponse.status, 201); const created = (await createdResponse.json()).user as { id: string; role: string }; assert.equal(created.role, "USER");
    const duplicate = await fetch(`${baseUrl}/api/admin/users`, { method: "POST", headers: headers(admin), body: JSON.stringify({ username, password: resetPassword, role: "USER" }) }); assert.equal(duplicate.status, 409); assert.equal((await duplicate.json()).error, "Username sudah digunakan.");
    const reset = await fetch(`${baseUrl}/api/admin/users/${created.id}`, { method: "PATCH", headers: headers(admin), body: JSON.stringify({ action: "reset-password", password: resetPassword }) }); assert.equal(reset.status, 200); assert.equal("password" in (await reset.json()).user, false);
    const deactivate = await fetch(`${baseUrl}/api/admin/users/${created.id}`, { method: "PATCH", headers: headers(admin), body: JSON.stringify({ action: "deactivate" }) }); assert.equal(deactivate.status, 200); assert.equal((await deactivate.json()).user.isActive, false);
    const activate = await fetch(`${baseUrl}/api/admin/users/${created.id}`, { method: "PATCH", headers: headers(admin), body: JSON.stringify({ action: "activate" }) }); assert.equal(activate.status, 200); assert.equal((await activate.json()).user.isActive, true);
    const selfDeactivate = await fetch(`${baseUrl}/api/admin/users/${admin.cookie ? (await (await fetch(`${baseUrl}/api/admin/users`, { headers: { cookie: admin.cookie } })).json()).users.find((entry: { username: string }) => entry.username === `it_uim_admin_${suffix}`).id : "0"}`, { method: "PATCH", headers: headers(admin), body: JSON.stringify({ action: "deactivate" }) }); assert.equal(selfDeactivate.status, 409); assert.equal((await selfDeactivate.json()).error, "Admin tidak dapat dinonaktifkan.");
    const adminList = await (await fetch(`${baseUrl}/api/admin/users`, { headers: { cookie: admin.cookie } })).json() as { users: Array<{ id: string; username: string }> }; const otherAdmin = adminList.users.find((entry) => entry.username === `it_uim_other_admin_${suffix}`)!; const otherAdminDeactivate = await fetch(`${baseUrl}/api/admin/users/${otherAdmin.id}`, { method: "PATCH", headers: headers(admin), body: JSON.stringify({ action: "deactivate" }) }); assert.equal(otherAdminDeactivate.status, 409); assert.equal((await otherAdminDeactivate.json()).error, "Admin tidak dapat dinonaktifkan.");
  } finally { if (server && server.exitCode === null) { if (process.platform === "win32" && server.pid) { spawnSync("taskkill", ["/PID", String(server.pid), "/T", "/F"], { windowsHide: true, stdio: "ignore" }); } else server.kill("SIGTERM"); } await dbAdmin.query("SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname = $1 AND pid <> pg_backend_pid()", [database]).catch(() => undefined); await dbAdmin.query(`DROP DATABASE IF EXISTS ${quote(database)}`).catch(() => undefined); await dbAdmin.end().catch(() => undefined); }
});
