import { NextResponse } from "next/server";
import { z } from "zod";
import { currentSession, hasValidCsrf } from "@/server/auth";
import { DateTimeInputError, parseWorkshopDateTime } from "@/server/datetime";
import { createStockOpname, listStockOpnames, StockOpnameServiceError } from "@/server/stock-opname-service";

const schema = z.object({ transactionAt: z.string() });
async function auth(request: Request, mutate = false) { const session = await currentSession(); if (!session) return { session: null, response: NextResponse.json({ error: "Autentikasi diperlukan." }, { status: 401 }) }; if (session.user.mustChangePassword) return { session: null, response: NextResponse.json({ error: "Ganti password sebelum melanjutkan." }, { status: 403 }) }; if (mutate && !(await hasValidCsrf(request, session))) return { session: null, response: NextResponse.json({ error: "Permintaan tidak valid." }, { status: 403 }) }; return { session, response: null }; }
function failure(error: unknown) { if (error instanceof DateTimeInputError) return NextResponse.json({ error: error.message }, { status: 400 }); if (error instanceof StockOpnameServiceError) return NextResponse.json({ error: error.message }, { status: error.kind === "NOT_FOUND" ? 404 : error.kind === "INVALID" || error.kind === "FUTURE_DATE" ? 400 : 409 }); throw error; }
export async function GET(request: Request) { const authenticated = await auth(request); if (authenticated.response) return authenticated.response; const url = new URL(request.url); const status = url.searchParams.get("status"); const search = url.searchParams.get("opnameNumber") ?? undefined; try { const rows = await listStockOpnames(authenticated.session!.user.role, { status: status === "REVISION" || status === "FINALIZED" || status === "APPROVED" ? status : undefined, search }); return NextResponse.json({ stockOpnames: rows }); } catch (error) { return failure(error); } }
export async function POST(request: Request) { const authenticated = await auth(request, true); if (authenticated.response) return authenticated.response; const key = request.headers.get("idempotency-key"); if (!key) return NextResponse.json({ error: "Kunci permintaan wajib disertakan." }, { status: 400 }); const parsed = schema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: "Data Stock Opname tidak valid." }, { status: 400 }); try { const stockOpname = await createStockOpname({ transactionAt: parseWorkshopDateTime(parsed.data.transactionAt) }, { id: authenticated.session!.user.id, username: authenticated.session!.user.username }, key, authenticated.session!.user.role); return NextResponse.json({ stockOpname }, { status: 201 }); } catch (error) { return failure(error); } }
