"use client";

import { useCallback, useEffect, useState } from "react";

type Preset = "today" | "week" | "month" | "custom";
type Part = { id: string; code: string; name: string; currentStock: string; minimumStock: string; isLow: boolean; isMinus: boolean };
type Bucket = { key: string; label: string; from: string; to: string; serviceRevenue?: string; slsRevenue?: string; totalRevenue?: string; grossProfit?: string };
type Dashboard = { period: { preset: Preset; from: string; to: string; timezone: string }; kpis: { serviceRevenue: string; slsRevenue: string; hppPenjualan: string; grossProfit: string; netProfit: string; expenseTotal: string; inventoryValue: string; serviceCount: number; slsCount: number; completedPurchaseCount: number; pendingPurchaseDraftCount: number; lowStockCount: number }; charts: { revenue: Bucket[]; grossProfit: Bucket[] }; monitoring: { lowStockParts: Part[] } };

const money = (value: string) => `Rp ${BigInt(value).toLocaleString("id-ID")}`;
const date = (value: string) => new Intl.DateTimeFormat("id-ID", { dateStyle: "medium" }).format(new Date(`${value}T00:00:00`));
const query = (report: string, dashboard: Dashboard) => `/reports?report=${report}&from=${dashboard.period.from}&to=${dashboard.period.to}`;

function MiniChart({ title, rows, series }: { title: string; rows: Bucket[]; series: Array<{ key: string; label: string; color: string }> }) {
  const values = rows.flatMap((row) => series.map((item) => Number(row[item.key as keyof Bucket] ?? 0))); const max = Math.max(1, ...values);
  return <section className="rounded border bg-white p-4"><h2 className="font-semibold">{title}</h2><div className="mt-4 flex h-48 items-end gap-1 overflow-x-auto border-b border-l p-3">{rows.map((row) => <div key={row.key} className="flex min-w-12 flex-1 items-end justify-center gap-1 self-stretch" title={row.label}>{series.map((item) => <div key={item.key} className="w-full rounded-t" style={{ height: `${Math.max(2, Number(row[item.key as keyof Bucket] ?? 0) / max * 100)}%`, backgroundColor: item.color }} />)}</div>)}</div><div className="mt-3 flex flex-wrap gap-4 text-xs">{series.map((item) => <span key={item.key}><i className="mr-1 inline-block h-2 w-2 rounded-full" style={{ backgroundColor: item.color }} />{item.label}</span>)}</div></section>;
}

export function DashboardClient({ workshopName, timezone }: { workshopName: string; timezone: string }) {
  const [preset, setPreset] = useState<Preset>("month"); const [from, setFrom] = useState(""); const [to, setTo] = useState(""); const [dashboard, setDashboard] = useState<Dashboard | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const params = new URLSearchParams({ preset }); if (preset === "custom") { params.set("from", from); params.set("to", to); } const response = await fetch(`/api/admin/dashboard?${params}`, { cache: "no-store" }); const result = await response.json(); if (!response.ok) throw new Error(result.error ?? "Dashboard gagal dimuat."); setDashboard(result.dashboard); if (!from) setFrom(result.dashboard.period.from); if (!to) setTo(result.dashboard.period.to); } catch (reason) { setError((reason as Error).message); } finally { setLoading(false); } }, [from, preset, to]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  const kpis = dashboard?.kpis;
  const cards = kpis ? [
    ["Service Revenue", money(kpis.serviceRevenue), query("services", dashboard)], ["SLS Revenue", money(kpis.slsRevenue), query("sls", dashboard)], ["HPP Penjualan", money(kpis.hppPenjualan)], ["Gross Profit", money(kpis.grossProfit)], ["Total Expense", money(kpis.expenseTotal), query("expenses", dashboard)], ["Net Profit", money(kpis.netProfit)], ["Nilai Persediaan", money(kpis.inventoryValue)], ["Service Count", String(kpis.serviceCount), query("services", dashboard)], ["SLS Count", String(kpis.slsCount), query("sls", dashboard)], ["Completed Purchase", String(kpis.completedPurchaseCount), query("purchases", dashboard)], ["Pending Purchase Draft", String(kpis.pendingPurchaseDraftCount), "/purchases"], ["Low Stock", String(kpis.lowStockCount), "/spareparts?filter=low"],
  ] as Array<[string, string, string | undefined]> : [];
  return <main className="mx-auto max-w-7xl p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><a href="/beranda" className="text-sm text-blue-700">← Beranda</a><h1 className="mt-3 text-2xl font-semibold">Dashboard</h1><p className="text-sm text-slate-600">{workshopName} · Timezone: {timezone}</p></div><button disabled={loading} onClick={() => void load()} className="rounded border px-3 py-2 disabled:opacity-50">{loading ? "Memuat…" : "Refresh"}</button></div><section className="my-5 flex flex-wrap items-end gap-3 rounded border bg-white p-4"><label className="grid gap-1 text-sm">Periode<select className="rounded border px-3 py-2" value={preset} onChange={(event) => setPreset(event.target.value as Preset)}><option value="today">Hari Ini</option><option value="week">Minggu Ini</option><option value="month">Bulan Ini</option><option value="custom">Custom</option></select></label>{preset === "custom" && <><label className="grid gap-1 text-sm">Dari<input className="rounded border px-3 py-2" type="date" value={from} onChange={(event) => setFrom(event.target.value)} /></label><label className="grid gap-1 text-sm">Sampai<input className="rounded border px-3 py-2" type="date" value={to} onChange={(event) => setTo(event.target.value)} /></label></>}<button disabled={loading} onClick={() => void load()} className="rounded bg-blue-700 px-4 py-2 text-white disabled:opacity-50">Terapkan</button></section>{error && <p role="alert" className="my-3 rounded bg-red-50 p-3 text-red-700">{error}</p>}{dashboard && <><p className="mb-3 text-sm text-slate-600">Periode: {date(dashboard.period.from)} s/d {date(dashboard.period.to)}</p><section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-6">{cards.map(([label, value, href]) => href ? <a key={label} href={href} className="rounded border bg-white p-4 transition hover:border-blue-500"><p className="text-sm text-slate-600">{label}</p><p className="mt-2 text-xl font-semibold">{value}</p></a> : <article key={label} className="rounded border bg-white p-4"><p className="text-sm text-slate-600">{label}</p><p className="mt-2 text-xl font-semibold">{value}</p></article>)}</section><section className="mt-6 grid gap-4 lg:grid-cols-2"><MiniChart title="Service + SLS Revenue" rows={dashboard.charts.revenue} series={[{ key: "serviceRevenue", label: "Service", color: "#2563eb" }, { key: "slsRevenue", label: "SLS", color: "#16a34a" }]} /><MiniChart title="Gross Profit" rows={dashboard.charts.grossProfit} series={[{ key: "grossProfit", label: "Gross Profit", color: "#9333ea" }]} /></section><section className="mt-6"><Monitoring title="Low Stock" parts={dashboard.monitoring.lowStockParts} /></section></>}</main>;
}

function Monitoring({ title, parts }: { title: string; parts: Part[] }) { return <section className="rounded border bg-white p-4"><div className="flex items-center justify-between"><h2 className="font-semibold">{title}</h2><a href="/spareparts?filter=low" className="text-sm text-blue-700">Lihat semua</a></div>{parts.length ? <ul className="mt-3 divide-y">{parts.slice(0, 10).map((part) => <li key={part.id} className="flex justify-between gap-3 py-2 text-sm"><span>{part.code} — {part.name}</span><span>{part.currentStock} / min {part.minimumStock}</span></li>)}</ul> : <p className="mt-3 text-sm text-slate-500">Tidak ada data.</p>}</section>; }
