"use client";

import { useState } from "react";

type Item = { lineNumber?: number; description: string; quantity: string; unitPrice: string; lineAmount?: string };
type Expense = { id: string; expenseNumber: string; transactionInput: string; transactionDisplay: string; status: "COMPLETED" | "CANCELED"; totalAmount: string; generalNote: string | null; externalReceiptNumber: string | null; items: Item[] };
const money = (value: string) => `Rp${BigInt(value).toLocaleString("id-ID")}`;
const csrf = () => document.cookie.split(";").map((item) => item.trim()).find((item) => item.startsWith("pb_csrf="))?.slice(8) ?? "";
async function requestJson(url: string, method: string, body?: unknown, key = crypto.randomUUID()) { const response = await fetch(url, { method, headers: { "content-type": "application/json", "x-csrf-token": csrf(), "idempotency-key": key }, body: body === undefined ? undefined : JSON.stringify(body) }); const result = await response.json().catch(() => ({})); if (!response.ok) throw new Error(result.error ?? "Permintaan gagal."); return result; }

export function ExpensesClient({ initialExpenses, initialCanceled, defaultDateTime }: { initialExpenses: Expense[]; initialCanceled: Expense[]; defaultDateTime: string }) {
  const [expenses, setExpenses] = useState(initialExpenses);
  const [canceled, setCanceled] = useState(initialCanceled);
  const [showCanceled, setShowCanceled] = useState(false);
  const [expandedExpenses, setExpandedExpenses] = useState<Set<string>>(new Set());
  const [editing, setEditing] = useState<Expense | null>(null);
  const [transactionAt, setTransactionAt] = useState(defaultDateTime);
  const [items, setItems] = useState<Item[]>([{ description: "", quantity: "1", unitPrice: "" }]);
  const [generalNote, setGeneralNote] = useState("");
  const [externalReceiptNumber, setExternalReceiptNumber] = useState("");
  const [preview, setPreview] = useState<{ items: Item[]; totalAmount: string } | null>(null);
  const [busy, setBusy] = useState(false);
  const [notice, setNotice] = useState("");

  const payload = () => ({ transactionAt, items: items.map(({ description, quantity, unitPrice }) => ({ description, quantity, unitPrice })), generalNote, externalReceiptNumber });
  const reset = () => { setEditing(null); setTransactionAt(defaultDateTime); setItems([{ description: "", quantity: "1", unitPrice: "" }]); setGeneralNote(""); setExternalReceiptNumber(""); setPreview(null); };
  const refresh = async () => { const [normal, canceledResult] = await Promise.all([fetch("/api/admin/expenses", { cache: "no-store" }), fetch("/api/admin/expenses/canceled", { cache: "no-store" })]); if (normal.ok) setExpenses((await normal.json()).expenses); if (canceledResult.ok) setCanceled((await canceledResult.json()).expenses); };
  const runPreview = async () => { setBusy(true); try { const result = await requestJson("/api/admin/expenses/preview", "POST", payload()); setPreview(result.preview); setNotice("Preview Expense berhasil. Belum ada data yang disimpan."); } catch (error) { setNotice((error as Error).message); } finally { setBusy(false); } };
  const save = async () => { setBusy(true); try { const result = await requestJson(editing ? `/api/admin/expenses/${editing.id}` : "/api/admin/expenses", editing ? "PATCH" : "POST", payload()); setNotice(editing ? "Expense berhasil diperbarui." : `Expense ${result.expense.expenseNumber} berhasil disimpan.`); reset(); await refresh(); } catch (error) { setNotice((error as Error).message); } finally { setBusy(false); } };
  const beginEdit = (expense: Expense) => { setEditing(expense); setTransactionAt(expense.transactionInput); setItems(expense.items.map((item) => ({ description: item.description, quantity: item.quantity, unitPrice: item.unitPrice }))); setGeneralNote(expense.generalNote ?? ""); setExternalReceiptNumber(expense.externalReceiptNumber ?? ""); setPreview(null); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const cancel = async (expense: Expense) => { if (!window.confirm(`Batalkan ${expense.expenseNumber}? Expense menjadi CANCELED dan tidak masuk perhitungan biaya.`)) return; setBusy(true); try { await requestJson(`/api/admin/expenses/${expense.id}/cancel`, "POST"); setNotice("Expense dibatalkan."); await refresh(); } catch (error) { setNotice((error as Error).message); } finally { setBusy(false); } };
  const toggleExpenseDetails = (expenseId: string) => { setExpandedExpenses((old) => { const next = new Set(old); if (next.has(expenseId)) next.delete(expenseId); else next.add(expenseId); return next; }); };
  const updateItem = (index: number, field: keyof Item, value: string) => { setItems((old) => old.map((item, itemIndex) => itemIndex === index ? { ...item, [field]: value } : item)); setPreview(null); };

  return <main className="mx-auto max-w-6xl p-6"><a href="/beranda" className="text-sm text-blue-700">← Beranda</a><h1 className="mt-3 text-2xl font-semibold">Expense</h1><p className="mt-2 text-sm text-slate-600">Expense hanya dapat dikelola Admin dan tidak memengaruhi stok.</p>{notice && <p role="status" className="my-3 rounded bg-slate-100 p-3">{notice}</p>}
    <section className="my-5 rounded border bg-white p-4"><h2 className="font-semibold">{editing ? `Edit ${editing.expenseNumber}` : "Buat Expense"}</h2><div className="mt-3 grid gap-3 md:grid-cols-3"><label className="grid gap-1 text-sm">Tanggal dan waktu<input className="rounded border px-3 py-2" type="datetime-local" value={transactionAt} onChange={(event) => { setTransactionAt(event.target.value); setPreview(null); }} /></label><label className="grid gap-1 text-sm">Catatan umum<input className="rounded border px-3 py-2" value={generalNote} onChange={(event) => { setGeneralNote(event.target.value); setPreview(null); }} /></label><label className="grid gap-1 text-sm">Nomor bukti eksternal<input className="rounded border px-3 py-2" value={externalReceiptNumber} onChange={(event) => { setExternalReceiptNumber(event.target.value); setPreview(null); }} /></label></div>
      <div className="mt-4 space-y-3">{items.map((item, index) => <div key={index} className="grid gap-2 rounded border p-3 md:grid-cols-[2fr_1fr_1fr_auto]"><label className="grid gap-1 text-sm">Deskripsi<input className="rounded border px-2 py-2" value={item.description} onChange={(event) => updateItem(index, "description", event.target.value)} /></label><label className="grid gap-1 text-sm">Quantity<input className="rounded border px-2 py-2" inputMode="decimal" placeholder="0.000" value={item.quantity} onChange={(event) => updateItem(index, "quantity", event.target.value)} /></label><label className="grid gap-1 text-sm">Harga satuan (Rp)<input className="rounded border px-2 py-2" inputMode="numeric" value={item.unitPrice} onChange={(event) => updateItem(index, "unitPrice", event.target.value)} /></label><button className="self-end rounded border px-3 py-2 disabled:opacity-50" disabled={items.length <= 1} onClick={() => { setItems((old) => old.filter((_, itemIndex) => itemIndex !== index)); setPreview(null); }}>Hapus</button></div>)}</div>
      <div className="mt-3 flex flex-wrap gap-2"><button className="rounded border px-3 py-2" onClick={() => setItems((old) => [...old, { description: "", quantity: "1", unitPrice: "" }])}>Tambah item</button><button disabled={busy} className="rounded border px-4 py-2 disabled:opacity-50" onClick={() => void runPreview()}>Preview</button>{preview && <button disabled={busy} className="rounded bg-blue-700 px-4 py-2 text-white disabled:opacity-50" onClick={() => void save()}>{busy ? "Menyimpan…" : editing ? "Simpan Perubahan" : "Simpan Expense"}</button>}{editing && <button className="rounded border px-4 py-2" onClick={reset}>Batal</button>}</div>
      {preview && <div className="mt-4 rounded bg-blue-50 p-3 text-sm"><strong>Preview total: {money(preview.totalAmount)}</strong><ul className="mt-2">{preview.items.map((item, index) => <li key={index}>{item.description}: {item.quantity} × {money(item.unitPrice)} = {money(item.lineAmount ?? "0")}</li>)}</ul></div>}
    </section>
    <div className="mb-3 flex gap-2"><button className={`rounded border px-3 py-2 ${!showCanceled ? "bg-slate-100" : ""}`} onClick={() => setShowCanceled(false)}>Completed</button><button className={`rounded border px-3 py-2 ${showCanceled ? "bg-slate-100" : ""}`} onClick={() => setShowCanceled(true)}>Dibatalkan</button></div>
     <section className="space-y-3">{(showCanceled ? canceled : expenses).map((expense) => { const detailsOpen = expandedExpenses.has(expense.id); return <article key={expense.id} className="rounded border bg-white p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-semibold">{expense.expenseNumber} · {expense.status}</h2><p className="text-sm text-slate-600">{expense.transactionDisplay}{expense.externalReceiptNumber ? ` · Bukti ${expense.externalReceiptNumber}` : ""}</p></div><strong>{money(expense.totalAmount)}</strong></div><div className="mt-3"><button className="rounded border px-3 py-1" onClick={() => toggleExpenseDetails(expense.id)}>{detailsOpen ? "Tutup Detail" : "Detail"}</button></div>{detailsOpen && <ul className="mt-3 divide-y">{expense.items.map((item) => <li key={item.lineNumber} className="flex flex-wrap justify-between gap-2 py-2 text-sm"><span>{item.description} × {item.quantity}</span><span>{money(item.lineAmount ?? "0")}</span></li>)}</ul>}{expense.generalNote && <p className="mt-2 text-sm text-slate-600">Catatan: {expense.generalNote}</p>}{!showCanceled && <div className="mt-3 flex gap-2"><button disabled={busy} className="rounded border px-3 py-1" onClick={() => beginEdit(expense)}>Edit</button><button disabled={busy} className="rounded border border-red-300 px-3 py-1 text-red-800" onClick={() => void cancel(expense)}>Batalkan</button></div>}</article>; })}{!(showCanceled ? canceled : expenses).length && <p className="rounded border bg-white p-4 text-slate-600">Belum ada Expense.</p>}</section>
  </main>;
}
