import { NextResponse } from "next/server";
import { z } from "zod";
import { requireAdmin } from "@/server/auth";
import { DateTimeInputError, parseWorkshopDateTime } from "@/server/datetime";
import { ExpenseServiceError, getExpense, updateExpense } from "@/server/expense-service";
const bodySchema = z.object({ transactionAt: z.string(), items: z.array(z.object({ description: z.string(), quantity: z.string(), unitPrice: z.string() })), generalNote: z.string().optional(), externalReceiptNumber: z.string().optional() });
function parseId(value: string) { if (!/^\d{1,19}$/.test(value) || BigInt(value) <= 0n) return null; return BigInt(value); }
function failure(error: unknown) { if (error instanceof ExpenseServiceError) return NextResponse.json({ error: error.message }, { status: error.kind === "NOT_FOUND" ? 404 : error.kind === "INVALID" || error.kind === "FUTURE_DATE" ? 400 : 409 }); if (error instanceof DateTimeInputError) return NextResponse.json({ error: error.message }, { status: 400 }); throw error; }
export async function GET(request: Request, context: { params: Promise<{ id: string }> }) { const auth = await requireAdmin(request, false); if (auth.response) return auth.response; const id = parseId((await context.params).id); if (!id) return NextResponse.json({ error: "Expense tidak ditemukan." }, { status: 404 }); const expense = await getExpense(id); return expense ? NextResponse.json({ expense }) : NextResponse.json({ error: "Expense tidak ditemukan." }, { status: 404 }); }
export async function PATCH(request: Request, context: { params: Promise<{ id: string }> }) { const auth = await requireAdmin(request); if (auth.response) return auth.response; const id = parseId((await context.params).id); if (!id) return NextResponse.json({ error: "Expense tidak ditemukan." }, { status: 404 }); const key = request.headers.get("idempotency-key"); if (!key) return NextResponse.json({ error: "Kunci permintaan wajib disertakan." }, { status: 400 }); const parsed = bodySchema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: "Data Expense tidak valid." }, { status: 400 }); try { const expense = await updateExpense(id, { ...parsed.data, transactionAt: parseWorkshopDateTime(parsed.data.transactionAt) }, { id: auth.session!.user.id, username: auth.session!.user.username }, key); return NextResponse.json({ expense }); } catch (error) { return failure(error); } }
